# Run `travis lint` when changing this file to avoid breaking the build.
# Default JDK is really old: 1.8.0_31; Trusty's is less old: 1.8.0_51
# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: false
dist: trusty

cache:
  directories:
  - $HOME/.m2

language: java

jdk:
  - oraclejdk8

addons:
  apt:
    packages:
      - oracle-java8-installer

before_install:
  # allocate commits to CI, not the owner of the deploy key
  - git config user.name "opentracingci"
  - git config user.email "opentracingci+opentracing@googlegroups.com"
  # setup https authentication credentials, used by ./mvnw release:prepare
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://$GH_TOKEN:@github.com" > .git/credentials

install:
  # Override default travis to use the maven wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - ./travis/publish.sh

# Don't build release tags. This avoids publish conflicts because the version commit exists both on master and the release tag.
# See https://github.com/travis-ci/travis-ci/issues/1532
branches:
  except:
    - /^[0-9]/

env:
  global:
  # Ex. travis encrypt BINTRAY_USER=your_github_account
  - secure: "oYJ9i0RBZKVHB77zVutOxPlm+cEpDH/XbJ22AFtPNQ6X8Ns0TPO1qyYQ1u42SGBLzLT1w5uHSk9dNS4iWTuNk2JgIu7rjh0VVxBoI+JhqAWgPEBdXyUt4CbUr7EktGNIlv50eDfXAcrH01cteDgsCtE2mi1GIXNUmoxUfy5QjrZa+7AkmdaICmoRTXE+z55/WxkyRFQAI+WKhVTiUS3VcWLrK/txcfsTejNCLVFQsZIUUi7y61v+avi/rCpRcCg6HlL4ApwUnx+XKWic7gP2OJpxw/Jd6FyH1VS3WEXWqQ9xNNcGEzzsJ5awqjKKJfOo+nnVJQvSN5MZ0WS11ysfpgnF/TEwxA5outfD6a29/n3KiJVkk9Ozv+Qmdf651XqGIAMDqw5e/cI0h81qCyEu9GgPcvvRfeeXdv94ELVLaF6MXvG984gb+tnLnNP9+V3+DSNiQMOY3GDKEljuYwxADMX0gMblUOW9sX7aIR00TSSDf48+nrdDgxT6j7373NAtFYOpcil4ygQM03WpAtwrqwoDs2qyjH5v+kGN377xeJAipiPh7bkzHWFlsysjcKHQd4rbsnvAyUnf4yfvOEaxSW0VLGhRTDbHEVq48RKAcid4Jb9tp3weqkPT2ZVS9nLG7LJ9eBurFztRtWa81Q3i0J+PijvJGnT1bgwnHTMtJDY="
  # Ex. travis encrypt BINTRAY_KEY=xxx-https://bintray.com/profile/edit-xxx --add
  - secure: "gxs+8L2RzI+/OzDniBVkqJoq4iJ5HkVpfrrgx2fVbReN2si/zjp/J4C0AqYsSpNZRbs8NGSlqI4+vgIdRKum8rEw3M0GigR1IpLcCeQ21XEpZ57XA8nOdGmm9wtuy3SqE/r3nXotQ6qqEu5QRDG35asuzKcN61ieHbXnQLO1Vd5JGf5OeJCZRTpi+GDj6y9MuW4AWta3O8ljjdQSVSg7He799jKKshWkIHIs2qVpN+sIVrOBiR0tY5vBzURAcJoK7jUc/DSCfxx29aL0j8VDnvWKmh+MpJw3GnNP7V8xJM3iUfnLzjgoFIhfGdoEhhVnhFgWTwZSks7s6bk/xTIw96YDIo9XrlVcbU2R3tlpz7QAIOo89FIge45LqmoChdoJR+NNWqqbQ5u42n1sRjVDbpk2pHQiEhL/9nYDuvY9jtOAN+sd4AXi/j4iQTkspJvLzn6s0MK8Zk33G5Hr73N7kVH1+zNhbCC6DBicq2sQKQl7NifJlZfHAObzrVve/o/AqzMQKjrF9PMV7K+jPoXmGRys2N2wAvghkCfcFvEj7Pc6FkKS9x/Y8LYLba61NB9xOc5LOSMOqNFjH5GB6r7Cvn/dK5ztR4SIz7WVyY4bfGaSv8+vc7SeFUpKikm8HKAF9aP1f0nVOaVTVLwy4v+eSWeAto4KZrwEp5bD8SVVMrA="
  # Ex. travis encrypt GH_TOKEN=XXX-https://github.com/settings/tokens-XXX --add
  - secure: "carcMx3y+a/v/SnwTJYz3384YFJoobJka+ANvz4wMUA52hj6C57h/EVMNjdYl2CM9X/0R4QfekztA321a/K/T8mI/bCr0BqAEDaSKfdgv2VEpm1k0fIZO/cmHgatQvKTWAPoSDIbqbzN/uJrOwbcXGZlZnIblJnaVLw0jJJCs/KW75uhyRNM5YQQCuXhpEz6KhrA8Ci8uI+b6kOzrJ6Js2IFfOFun6onvLx1QabY9v07bfic7E+gKA87DNkKTZBEJlkQYEg4pxqI5ao9FMi395Xp9xyqMSzU5DIMoW49qhAKy3hsiLckK6VR5KT5u3lyJUPH59z8eNZQdnxXlT4V/1bkLjB92DHyt6XM3cjRcmYLmWiOy/Fzl1tJAzcQIIODGk/vntwBUDzN3RUbTpcWYuVatQslX+X88KYWQP7RCStMV2pRophDFBye/tmuCuKtGRpIOBMyY4wMUhWqS0gIQwf4jLGGc9xJDLgVE8nCDDSDdyoeDUD9sb7zjki1ot9sbqfm49wrBbOGQAA3dctaNqU4H/FQX6U9Icu/rHdDHTGF7RM04OjSRCyYYXtqh76OOnra5lH7OMfHHJOWmyBVU8XdHgX6r5wvo35Ccw0nd7BYLbekrUORTrkL76HaaLkW/UaY+6w2KPhRykjhif3wg2i6HoqU5feO8lnO1kOwwuM="
  # Ex. travis encrypt SONATYPE_USER=your_sonatype_account
  - secure: "UtIE6AbRVttafn2H7JFiv8Dz926lUxnXokT2jkKcwoPsRSEZfTy5n0pQ+ianq9d2Id6wWiVQc/9JU1R8oJIYNKTJA4Qw1Yhz9z8IyDQww4K8wEAM0n6bq+7z9u63G+VtVCxydt+PJtT9qMtVLjU4NTIohBCHZbYmq0Us7oMK+4hIMVh6jt8M9aAfpiIL6Vdpl7J7Kh0/+1FuScVwgucpDnaRIVdQEFxkSqYRD/R+loNUt/mI5qw6nh4052PF2SBeMF6JT+zBffE2jQ+uGoG3FUb0ciJWU+xuQCE/Ee0J7pEUrQN8xqnUFSNdlL7D2YK1ShcvseNW3ieztl8gwFo8Nh2g6GuazT3uDwDIZknl2lw5pXB9YD51tI9wsXueHnKHsP3zGCAgIsLi19ZnifJpml0w5OX1n0DGNSAXeyUoO6v/UObmzncQqM0aZH2wyjIyOSNhLFMKKuUpcdecoqPtFEq+OVQTJ+zT3Ick6dwNcgLy4P/GsDXYNb6zBs2R67B9DVpLmoiwcY4b2fxfrVp8Xh3xQAxo9i2nBv4zPPu9JkT/BVTkZEGeLtAuI0AuGhqsYD9fvGz5pZxvDfO3hH11Q05G9gkKjlpHCW64bhQpGkGgVDToE4szOAwCxaywTESTeYQGRWEaMZ2aBoqkB8Qk4DTe02j55ADAVfJZPwcq6JA="
  # Ex. travis encrypt SONATYPE_PASSWORD=your_sonatype_password
  - secure: "VipjtpC5bRquet8Y7y2YLaaHpLOQ+fDz5vV0C8lqPAohxOEWZe7T1M8EzxHt3YKc5yoxMUvxcF8WFKnsdKXZVD3siH40wYDTeCosB8egtABqdgvih39ewBFqhohR9z5r90AkN6GVNNBUufKISIh2RI2tsyn1dhlbSbNfSjPxpcPRj5L5OA71/uI6EAHiumIFt+0zO9owI8aQcLyM0REQKSSt014I9VyG0ZTtTl1TxVJrPlHGlh/OZ0v1XeadKRq9e01uGsbC8Aoq3m5v4RoEEOzSmsid29VQJkn9nCR2+YbM3RSxObsWemVxw1ROdzbrJvxEWpIcwXToLOgdB7WESATp6JcKmqwCNWRqGJjYuG7VrrjN8zhhMAWjRWSbH3zcrky3H0G5VfVF/voU8F11G0Y6HpFKbsGJrUZTp6q7jtNiP2FyZyq5uA6HhOvquphkHklostDuyZXHTHQfNAQrSZb/TU5BkZ26P6NGEI/gNvAPKmEwveptowFDaTxnLrqsJeuL8XohMAamoRPoFKKUj88URwuhekla3Y2HICj8Vw79ZeLb17IFLMTfh0qCEQOPTJ7yfmaj6VrUwllfulEj6Sumke2mK/zrOgaLEnl4VGYRfVdnuaTYPrE+xdB229CoVrvwD3J4JToi9hUkElUgGD5SOBD9h6EJJUMi6tHNZuM="
